// flow-typed signature: e9767b76a95a460412c772225180aa1e
// flow-typed version: <<STUB>>/file-stream-reader_v^1.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-stream-reader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-stream-reader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'file-stream-reader/index' {
  declare module.exports: $Exports<'file-stream-reader'>;
}
declare module 'file-stream-reader/index.js' {
  declare module.exports: $Exports<'file-stream-reader'>;
}
